# Generated by Django 5.2.9 on 2025-12-06 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_topic_parent_alter_topic_slug_alter_topic_title"),
        ("quizzes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="correct_option",
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name="question",
            name="option_c",
            field=models.CharField(default="None", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="option_d",
            field=models.CharField(default="None", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="quiz",
            name="topic",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz",
                to="courses.topic",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="total_marks",
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name="userquizresult",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
