# Generated by Django 5.2.9 on 2025-12-06 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_topic_options_remove_topic_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtopics",
                to="courses.topic",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="topic",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
