# Generated by Django 5.2.9 on 2026-01-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_topic_parent_alter_topic_slug_alter_topic_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="topics/"),
        ),
    ]
